security:
  oauth2:
    client:
      clientId: 426726941371404
      clientSecret: a0466b72632a8155ccf8ad0103c8a11d
      redirect_uri: localhost:8080/
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
spring:
  main:
    allow-bean-definition-overriding: true
server:
  port: ${PORT:8080}
